"""Add Invoice Settlement Tables

Revision ID: d77b07f1f7fd
Revises: 2d8218832bf5
Create Date: 2026-01-03 10:14:04.276801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77b07f1f7fd'
down_revision: Union[str, Sequence[str], None] = '2d8218832bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_allocation_id'), 'payment_allocation', ['id'], unique=False)
    op.add_column('invoice', sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoice', sa.Column('payment_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'payment_status')
    op.drop_column('invoice', 'paid_amount')
    op.drop_index(op.f('ix_payment_allocation_id'), table_name='payment_allocation')
    op.drop_table('payment_allocation')
    # ### end Alembic commands ###
