"""Add photo_path to employee_profiles

Revision ID: e7cc317a1b92
Revises: 5207b9083425
Create Date: 2026-01-04 23:02:24.072799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7cc317a1b92'
down_revision: Union[str, Sequence[str], None] = '5207b9083425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('photo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_profiles', 'photo_path')
    # ### end Alembic commands ###
