"""add_challan_item_ids_to_invoice_item

Revision ID: 04bbde8045da
Revises: 7fee0170dc03
Create Date: 2026-01-10 12:22:47.453049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bbde8045da'
down_revision: Union[str, Sequence[str], None] = '7fee0170dc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('challan_item_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'challan_item_ids')
    # ### end Alembic commands ###
