"""Add challan_number and enhanced fields to delivery_challan

Revision ID: 1cc390b6b53e
Revises: 6a82582f8d4a
Create Date: 2025-12-29 19:53:43.438445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cc390b6b53e'
down_revision: Union[str, Sequence[str], None] = '6a82582f8d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add challan_number as nullable first
    op.add_column('delivery_challan', sa.Column('challan_number', sa.String(length=50), nullable=True))
    
    # Update existing records with generated challan numbers
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE delivery_challan 
        SET challan_number = 'CH-' || LPAD(id::text, 3, '0')
        WHERE challan_number IS NULL
    """))
    
    # Now make it non-nullable and add unique constraint
    op.alter_column('delivery_challan', 'challan_number', nullable=False)
    op.create_index(op.f('ix_delivery_challan_challan_number'), 'delivery_challan', ['challan_number'], unique=True)
    
    op.add_column('delivery_challan', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('delivery_challan', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'))
    op.alter_column('delivery_challan', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_challan', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('items', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_delivery_challan_challan_number'), table_name='delivery_challan')
    op.alter_column('delivery_challan', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_challan', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('delivery_challan', 'is_active')
    op.drop_column('delivery_challan', 'notes')
    op.drop_column('delivery_challan', 'challan_number')
    # ### end Alembic commands ###
