"""remove_fy_from_party

Revision ID: 2b7d23ffcf24
Revises: 99b641c02df3
Create Date: 2026-07-18 10:59:17.227154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7d23ffcf24'
down_revision: Union[str, Sequence[str], None] = '99b641c02df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('party_financial_year_id_fkey'), 'party', type_='foreignkey')
    op.drop_column('party', 'financial_year_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('party_financial_year_id_fkey'), 'party', 'financial_year', ['financial_year_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
