"""Add current_stock and indexes

Revision ID: 484a80e71c6d
Revises: 2b7d23ffcf24
Create Date: 2026-07-18 13:23:50.752381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484a80e71c6d'
down_revision: Union[str, Sequence[str], None] = '2b7d23ffcf24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_invoice_company_fy_status', 'invoice', ['company_id', 'financial_year_id', 'status'], unique=False)
    op.create_index('idx_invoice_date', 'invoice', ['invoice_date'], unique=False)
    op.create_index('idx_invoice_party_payment_status', 'invoice', ['party_id', 'payment_status'], unique=False)
    op.add_column('items', sa.Column('current_stock', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False))
    
    # 1. Backfill current_stock from existing stock_transactions
    op.execute("""
        UPDATE items
        SET current_stock = COALESCE((
            SELECT SUM(
                CASE WHEN transaction_type = 'IN' THEN quantity
                     WHEN transaction_type = 'OUT' THEN -quantity
                     ELSE 0 END
            )
            FROM stock_transactions
            WHERE stock_transactions.item_id = items.id
        ), 0)
    """)

    # 2. Create Trigger Function
    op.execute("""
        CREATE OR REPLACE FUNCTION update_item_stock()
        RETURNS TRIGGER AS $$
        BEGIN
            IF (TG_OP = 'DELETE') THEN
                IF (OLD.transaction_type = 'IN') THEN
                    UPDATE items SET current_stock = current_stock - OLD.quantity WHERE id = OLD.item_id;
                ELSIF (OLD.transaction_type = 'OUT') THEN
                    UPDATE items SET current_stock = current_stock + OLD.quantity WHERE id = OLD.item_id;
                END IF;
                RETURN OLD;
            ELSIF (TG_OP = 'INSERT') THEN
                IF (NEW.transaction_type = 'IN') THEN
                    UPDATE items SET current_stock = current_stock + NEW.quantity WHERE id = NEW.item_id;
                ELSIF (NEW.transaction_type = 'OUT') THEN
                    UPDATE items SET current_stock = current_stock - NEW.quantity WHERE id = NEW.item_id;
                END IF;
                RETURN NEW;
            ELSIF (TG_OP = 'UPDATE') THEN
                IF (OLD.transaction_type = 'IN') THEN
                    UPDATE items SET current_stock = current_stock - OLD.quantity WHERE id = OLD.item_id;
                ELSIF (OLD.transaction_type = 'OUT') THEN
                    UPDATE items SET current_stock = current_stock + OLD.quantity WHERE id = OLD.item_id;
                END IF;
                IF (NEW.transaction_type = 'IN') THEN
                    UPDATE items SET current_stock = current_stock + NEW.quantity WHERE id = NEW.item_id;
                ELSIF (NEW.transaction_type = 'OUT') THEN
                    UPDATE items SET current_stock = current_stock - NEW.quantity WHERE id = NEW.item_id;
                END IF;
                RETURN NEW;
            END IF;
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # 3. Attach Trigger
    op.execute("""
        CREATE TRIGGER trg_stock_update
        AFTER INSERT OR UPDATE OR DELETE ON stock_transactions
        FOR EACH ROW EXECUTE FUNCTION update_item_stock();
    """)
    op.create_index('idx_payment_company_party', 'payments', ['company_id', 'party_id'], unique=False)
    op.create_index('idx_payment_date', 'payments', ['payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_date', table_name='payments')
    op.drop_index('idx_payment_company_party', table_name='payments')
    op.drop_column('items', 'current_stock')
    op.drop_index('idx_invoice_party_payment_status', table_name='invoice')
    op.drop_index('idx_invoice_date', table_name='invoice')
    op.drop_index('idx_invoice_company_fy_status', table_name='invoice')

    # Drop Trigger and Function
    op.execute("DROP TRIGGER IF EXISTS trg_stock_update ON stock_transactions;")
    op.execute("DROP FUNCTION IF EXISTS update_item_stock();")
    # ### end Alembic commands ###
