"""Add part_no to items

Revision ID: 4a6c8b9d2e1f
Revises: 3f533a37-63ab-4e7a-95d0-e8e569c5a6f9
Create Date: 2026-02-13 13:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6c8b9d2e1f'
down_revision = '511ff80c433b'  # Fixed to point to the latest merge
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('part_no', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'part_no')
    # ### end Alembic commands ###
