"""Add enable_tds to employee_profile with boolean fix

Revision ID: 590f0e754be6
Revises: f6af60b8806c
Create Date: 2026-01-17 22:58:39.117188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590f0e754be6'
down_revision: Union[str, Sequence[str], None] = 'f6af60b8806c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('enable_tds', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_profiles', 'enable_tds')
    # ### end Alembic commands ###
