"""Add client_status and client_notes to DeliveryChallan

Revision ID: 7aa9c0bffbb1
Revises: f218719571ee
Create Date: 2026-07-20 12:58:17.545115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa9c0bffbb1'
down_revision: Union[str, Sequence[str], None] = 'f218719571ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_challan', sa.Column('client_status', sa.String(length=20), nullable=True))
    op.add_column('delivery_challan', sa.Column('client_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_challan', 'client_notes')
    op.drop_column('delivery_challan', 'client_status')
    # ### end Alembic commands ###
