"""Add_invoice_fields

Revision ID: 86b3b1a4dac0
Revises: b0981aac8661
Create Date: 2026-01-02 08:23:11.652059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b3b1a4dac0'
down_revision: Union[str, Sequence[str], None] = 'b0981aac8661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('invoice_number', sa.String(length=50), nullable=False))
    op.add_column('invoice', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('invoice', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('invoice', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_invoice_invoice_number'), 'invoice', ['invoice_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_invoice_number'), table_name='invoice')
    op.drop_column('invoice', 'notes')
    op.drop_column('invoice', 'status')
    op.drop_column('invoice', 'due_date')
    op.drop_column('invoice', 'invoice_number')
    # ### end Alembic commands ###
