"""Add working_days and process_id to delivery challan

Revision ID: 8d663c9604de
Revises: e07f06491ddb
Create Date: 2025-12-29 20:49:50.059470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d663c9604de'
down_revision: Union[str, Sequence[str], None] = 'e07f06491ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_challan', sa.Column('working_days', sa.Integer(), nullable=True))
    op.add_column('delivery_challan_items', sa.Column('process_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'delivery_challan_items', 'processes', ['process_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_challan_items', type_='foreignkey')
    op.drop_column('delivery_challan_items', 'process_id')
    op.drop_column('delivery_challan', 'working_days')
    # ### end Alembic commands ###
