"""Add off_days to company

Revision ID: 973081014829
Revises: 5ebf5d1aad1f
Create Date: 2026-01-17 22:24:26.968661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '973081014829'
down_revision: Union[str, Sequence[str], None] = '5ebf5d1aad1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('off_days', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'off_days')
    # ### end Alembic commands ###
