"""Add tds_percentage to employee_profile

Revision ID: 9901dc4cc1bd
Revises: 973081014829
Create Date: 2026-01-17 22:38:26.968661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9901dc4cc1bd'
down_revision: Union[str, Sequence[str], None] = '973081014829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('tds_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_profiles', 'tds_percentage')
    # ### end Alembic commands ###
