"""Add feature_flags to subscription_plans

Revision ID: 99b641c02df3
Revises: 4c7a63732a64
Create Date: 2026-02-25 10:01:45.372904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99b641c02df3'
down_revision: Union[str, Sequence[str], None] = '4c7a63732a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_logins_id'), table_name='client_logins')
    op.drop_index(op.f('ix_client_logins_username'), table_name='client_logins')
    op.drop_table('client_logins')
    op.drop_index(op.f('ix_pdi_report_id'), table_name='pdi_report')
    op.drop_table('pdi_report')
    op.add_column('subscription_plans', sa.Column('feature_flags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'feature_flags')
    op.create_table('pdi_report',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inspection_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('inspector_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('checklist', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parameters_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dimensions_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['challan_id'], ['delivery_challan.id'], name=op.f('pdi_report_challan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pdi_report_pkey')),
    sa.UniqueConstraint('challan_id', name=op.f('pdi_report_challan_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pdi_report_id'), 'pdi_report', ['id'], unique=False)
    op.create_table('client_logins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('client_logins_party_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('client_logins_pkey')),
    sa.UniqueConstraint('party_id', name=op.f('client_logins_party_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_client_logins_username'), 'client_logins', ['username'], unique=True)
    op.create_index(op.f('ix_client_logins_id'), 'client_logins', ['id'], unique=False)
    # ### end Alembic commands ###
