"""Fix Challan Number Uniqueness

Revision ID: b0981aac8661
Revises: 4214a515fff9
Create Date: 2026-01-01 11:20:51.320586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0981aac8661'
down_revision: Union[str, Sequence[str], None] = '4214a515fff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_challan_challan_number'), table_name='delivery_challan')
    op.create_index(op.f('ix_delivery_challan_challan_number'), 'delivery_challan', ['challan_number'], unique=False)
    op.create_unique_constraint('uix_company_fy_challan_number', 'delivery_challan', ['company_id', 'financial_year_id', 'challan_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_company_fy_challan_number', 'delivery_challan', type_='unique')
    op.drop_index(op.f('ix_delivery_challan_challan_number'), table_name='delivery_challan')
    op.create_index(op.f('ix_delivery_challan_challan_number'), 'delivery_challan', ['challan_number'], unique=True)
    # ### end Alembic commands ###
