"""add_rbac_system

Revision ID: c2534155eb06
Revises: a0d7eb1fc6df
Create Date: 2026-01-16 12:07:35.672842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2534155eb06'
down_revision: Union[str, Sequence[str], None] = 'a0d7eb1fc6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    
    # Get connection for operations
    connection = op.get_bind()
    
    # Add new columns directly (not in batch mode to avoid circular dependency)
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('legacy_role', sa.String(length=50), nullable=True))
    
    # Migrate existing role enum to legacy_role string
    connection.execute(sa.text("""
        UPDATE users 
        SET legacy_role = CASE 
            WHEN role = 'SUPER_ADMIN' THEN 'SUPER_ADMIN'
            WHEN role = 'COMPANY_ADMIN' THEN 'COMPANY_ADMIN'
            WHEN role = 'USER' THEN 'USER'
        END
    """))
    
    # Use batch mode only for dropping the old column and adding foreign key
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.create_foreign_key('fk_users_role_id', 'roles', ['role_id'], ['id'])
    
    # Seed Permissions
    permissions_data = [
        # Dashboard
        ('dashboard', 'view', 'dashboard.view', 'View dashboard'),
        
        # Invoices
        ('invoices', 'view', 'invoices.view', 'View invoices'),
        ('invoices', 'create', 'invoices.create', 'Create invoices'),
        ('invoices', 'edit', 'invoices.edit', 'Edit invoices'),
        ('invoices', 'delete', 'invoices.delete', 'Delete invoices'),
        ('invoices', 'approve', 'invoices.approve', 'Approve invoices'),
        
        # Parties
        ('parties', 'view', 'parties.view', 'View parties/customers'),
        ('parties', 'create', 'parties.create', 'Create parties'),
        ('parties', 'edit', 'parties.edit', 'Edit parties'),
        ('parties', 'delete', 'parties.delete', 'Delete parties'),
        
        # Items
        ('items', 'view', 'items.view', 'View items'),
        ('items', 'create', 'items.create', 'Create items'),
        ('items', 'edit', 'items.edit', 'Edit items'),
        ('items', 'delete', 'items.delete', 'Delete items'),
        
        # Expenses
        ('expenses', 'view', 'expenses.view', 'View expenses'),
        ('expenses', 'create', 'expenses.create', 'Create expenses'),
        ('expenses', 'edit', 'expenses.edit', 'Edit expenses'),
        ('expenses', 'delete', 'expenses.delete', 'Delete expenses'),
        ('expenses', 'approve', 'expenses.approve', 'Approve expenses'),
        
        # Payments
        ('payments', 'view', 'payments.view', 'View payments'),
        ('payments', 'create', 'payments.create', 'Create payments'),
        ('payments', 'edit', 'payments.edit', 'Edit payments'),
        ('payments', 'delete', 'payments.delete', 'Delete payments'),
        
        # Delivery Challans
        ('challans', 'view', 'challans.view', 'View delivery challans'),
        ('challans', 'create', 'challans.create', 'Create delivery challans'),
        ('challans', 'edit', 'challans.edit', 'Edit delivery challans'),
        ('challans', 'delete', 'challans.delete', 'Delete delivery challans'),
        ('challans', 'convert', 'challans.convert', 'Convert challan to invoice'),
        
        # Party Challans
        ('party_challans', 'view', 'party_challans.view', 'View party challans'),
        ('party_challans', 'create', 'party_challans.create', 'Create party challans'),
        ('party_challans', 'edit', 'party_challans.edit', 'Edit party challans'),
        ('party_challans', 'delete', 'party_challans.delete', 'Delete party challans'),
        
        # Employees
        ('employees', 'view', 'employees.view', 'View employees'),
        ('employees', 'create', 'employees.create', 'Create employees'),
        ('employees', 'edit', 'employees.edit', 'Edit employees'),
        ('employees', 'delete', 'employees.delete', 'Delete employees'),
        
        # Attendance
        ('attendance', 'view', 'attendance.view', 'View attendance'),
        ('attendance', 'create', 'attendance.create', 'Mark attendance'),
        ('attendance', 'edit', 'attendance.edit', 'Edit attendance'),
        
        # Salary
        ('salary', 'view', 'salary.view', 'View salary'),
        ('salary', 'create', 'salary.create', 'Process salary'),
        ('salary', 'approve', 'salary.approve', 'Approve salary'),
        
        # Reports
        ('reports', 'view', 'reports.view', 'View reports'),
        ('reports', 'export', 'reports.export', 'Export reports'),
        
        # Settings
        ('settings', 'view', 'settings.view', 'View settings'),
        ('settings', 'edit', 'settings.edit', 'Edit settings'),
        
        # Backup
        ('backup', 'view', 'backup.view', 'View backups'),
        ('backup', 'create', 'backup.create', 'Create backups'),
        ('backup', 'restore', 'backup.restore', 'Restore backups'),
        
        # Users
        ('users', 'view', 'users.view', 'View users'),
        ('users', 'create', 'users.create', 'Create users'),
        ('users', 'edit', 'users.edit', 'Edit users'),
        ('users', 'delete', 'users.delete', 'Delete users'),
        
        # Roles
        ('roles', 'view', 'roles.view', 'View roles'),
        ('roles', 'create', 'roles.create', 'Create roles'),
        ('roles', 'edit', 'roles.edit', 'Edit roles'),
        ('roles', 'delete', 'roles.delete', 'Delete roles'),
    ]
    
    for module, action, code, description in permissions_data:
        connection.execute(sa.text(
            "INSERT INTO permissions (module, action, code, description) VALUES (:module, :action, :code, :description)"
        ), {"module": module, "action": action, "code": code, "description": description})
    
    # Seed Roles
    roles_data = [
        (None, 'Super Admin', 'Full system access', True),
        (None, 'Company Admin', 'Full company access', True),
        (None, 'Accountant', 'Finance and accounting access', True),
        (None, 'Sales Manager', 'Sales and customer management', True),
        (None, 'Warehouse Manager', 'Inventory and warehouse management', True),
        (None, 'HR Manager', 'Human resources management', True),
        (None, 'Employee', 'Basic employee access', True),
    ]
    
    for company_id, name, description, is_system_role in roles_data:
        connection.execute(sa.text(
            "INSERT INTO roles (company_id, name, description, is_system_role, is_active) VALUES (:company_id, :name, :description, :is_system_role, :is_active)"
        ), {"company_id": company_id, "name": name, "description": description, "is_system_role": is_system_role, "is_active": True})
    
    # Assign permissions to roles
    # Get role and permission IDs
    super_admin_id = connection.execute(sa.text("SELECT id FROM roles WHERE name = 'Super Admin'")).scalar()
    company_admin_id = connection.execute(sa.text("SELECT id FROM roles WHERE name = 'Company Admin'")).scalar()
    accountant_id = connection.execute(sa.text("SELECT id FROM roles WHERE name = 'Accountant'")).scalar()
    sales_manager_id = connection.execute(sa.text("SELECT id FROM roles WHERE name = 'Sales Manager'")).scalar()
    warehouse_manager_id = connection.execute(sa.text("SELECT id FROM roles WHERE name = 'Warehouse Manager'")).scalar()
    hr_manager_id = connection.execute(sa.text("SELECT id FROM roles WHERE name = 'HR Manager'")).scalar()
    employee_id = connection.execute(sa.text("SELECT id FROM roles WHERE name = 'Employee'")).scalar()
    
    # Super Admin gets ALL permissions
    all_permissions = connection.execute(sa.text("SELECT id FROM permissions")).fetchall()
    for perm in all_permissions:
        connection.execute(sa.text(
            "INSERT INTO role_permissions (role_id, permission_id) VALUES (:role_id, :permission_id)"
        ), {"role_id": super_admin_id, "permission_id": perm[0]})
    
    # Company Admin gets all permissions except super admin specific ones
    for perm in all_permissions:
        connection.execute(sa.text(
            "INSERT INTO role_permissions (role_id, permission_id) VALUES (:role_id, :permission_id)"
        ), {"role_id": company_admin_id, "permission_id": perm[0]})
    
    # Accountant permissions
    accountant_perms = [
        'dashboard.view', 'invoices.view', 'invoices.create', 'invoices.edit',
        'parties.view', 'items.view', 'expenses.view', 'expenses.create', 'expenses.edit',
        'payments.view', 'payments.create', 'payments.edit', 'reports.view', 'reports.export'
    ]
    for perm_code in accountant_perms:
        perm_id = connection.execute(sa.text("SELECT id FROM permissions WHERE code = :code"), {"code": perm_code}).scalar()
        if perm_id:
            connection.execute(sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) VALUES (:role_id, :permission_id)"
            ), {"role_id": accountant_id, "permission_id": perm_id})
    
    # Sales Manager permissions
    sales_perms = [
        'dashboard.view', 'invoices.view', 'invoices.create', 'invoices.edit',
        'parties.view', 'parties.create', 'parties.edit', 'items.view',
        'challans.view', 'challans.create', 'challans.edit', 'challans.convert',
        'reports.view'
    ]
    for perm_code in sales_perms:
        perm_id = connection.execute(sa.text("SELECT id FROM permissions WHERE code = :code"), {"code": perm_code}).scalar()
        if perm_id:
            connection.execute(sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) VALUES (:role_id, :permission_id)"
            ), {"role_id": sales_manager_id, "permission_id": perm_id})
    
    # Warehouse Manager permissions
    warehouse_perms = [
        'dashboard.view', 'items.view', 'items.create', 'items.edit',
        'challans.view', 'challans.create', 'challans.edit',
        'party_challans.view', 'party_challans.create', 'party_challans.edit',
        'reports.view'
    ]
    for perm_code in warehouse_perms:
        perm_id = connection.execute(sa.text("SELECT id FROM permissions WHERE code = :code"), {"code": perm_code}).scalar()
        if perm_id:
            connection.execute(sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) VALUES (:role_id, :permission_id)"
            ), {"role_id": warehouse_manager_id, "permission_id": perm_id})
    
    # HR Manager permissions
    hr_perms = [
        'dashboard.view', 'employees.view', 'employees.create', 'employees.edit',
        'attendance.view', 'attendance.create', 'attendance.edit',
        'salary.view', 'salary.create', 'salary.approve', 'reports.view'
    ]
    for perm_code in hr_perms:
        perm_id = connection.execute(sa.text("SELECT id FROM permissions WHERE code = :code"), {"code": perm_code}).scalar()
        if perm_id:
            connection.execute(sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) VALUES (:role_id, :permission_id)"
            ), {"role_id": hr_manager_id, "permission_id": perm_id})
    
    # Employee permissions (basic)
    employee_perms = ['dashboard.view', 'attendance.view', 'salary.view']
    for perm_code in employee_perms:
        perm_id = connection.execute(sa.text("SELECT id FROM permissions WHERE code = :code"), {"code": perm_code}).scalar()
        if perm_id:
            connection.execute(sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) VALUES (:role_id, :permission_id)"
            ), {"role_id": employee_id, "permission_id": perm_id})
    
    # Migrate existing users to new role system
    connection.execute(sa.text("""
        UPDATE users 
        SET role_id = (
            SELECT id FROM roles WHERE name = CASE 
                WHEN users.legacy_role = 'SUPER_ADMIN' THEN 'Super Admin'
                WHEN users.legacy_role = 'COMPANY_ADMIN' THEN 'Company Admin'
                WHEN users.legacy_role = 'USER' THEN 'Employee'
                ELSE 'Employee'
            END
        )
        WHERE legacy_role IS NOT NULL
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=13), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'legacy_role')
    op.drop_column('users', 'role_id')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
