"""Add working_days and process_id to party challan

Revision ID: e07f06491ddb
Revises: f8ef8e112b60
Create Date: 2025-12-29 20:25:17.473592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07f06491ddb'
down_revision: Union[str, Sequence[str], None] = 'f8ef8e112b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party_challan', sa.Column('working_days', sa.Integer(), nullable=True))
    op.add_column('party_challan_items', sa.Column('process_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'party_challan_items', 'processes', ['process_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'party_challan_items', type_='foreignkey')
    op.drop_column('party_challan_items', 'process_id')
    op.drop_column('party_challan', 'working_days')
    # ### end Alembic commands ###
