"""add_barcode_to_items

Revision ID: ed5a1a1b4fab
Revises: 85ae387da108
Create Date: 2026-02-05 20:41:04.918081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed5a1a1b4fab'
down_revision: Union[str, Sequence[str], None] = '85ae387da108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_logins_id'), table_name='client_logins')
    op.drop_index(op.f('ix_client_logins_username'), table_name='client_logins')
    op.drop_table('client_logins')
    op.drop_index(op.f('ix_pdi_report_id'), table_name='pdi_report')
    op.drop_table('pdi_report')
    op.add_column('items', sa.Column('barcode', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'items', ['barcode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='unique')
    op.drop_column('items', 'barcode')
    op.create_table('pdi_report',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inspection_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('inspector_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('checklist', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['challan_id'], ['delivery_challan.id'], name=op.f('pdi_report_challan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pdi_report_pkey')),
    sa.UniqueConstraint('challan_id', name=op.f('pdi_report_challan_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pdi_report_id'), 'pdi_report', ['id'], unique=False)
    op.create_table('client_logins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('client_logins_party_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('client_logins_pkey')),
    sa.UniqueConstraint('party_id', name=op.f('client_logins_party_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_client_logins_username'), 'client_logins', ['username'], unique=True)
    op.create_index(op.f('ix_client_logins_id'), 'client_logins', ['id'], unique=False)
    # ### end Alembic commands ###
