"""add_pincode_to_company_and_party

Revision ID: f218719571ee
Revises: a3f9b2c1d8e7
Create Date: 2026-07-19 08:25:19.979978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f218719571ee'
down_revision: Union[str, Sequence[str], None] = 'a3f9b2c1d8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('pincode', sa.String(length=6), nullable=True))
    op.add_column('party', sa.Column('pincode', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party', 'pincode')
    op.drop_column('company', 'pincode')
    # ### end Alembic commands ###
