"""Add professional_tax to employee_profile

Revision ID: f6af60b8806c
Revises: 9901dc4cc1bd
Create Date: 2026-01-17 22:49:03.968661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6af60b8806c'
down_revision: Union[str, Sequence[str], None] = '9901dc4cc1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('professional_tax', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_profiles', 'professional_tax')
    # ### end Alembic commands ###
